server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: Ysszljyx1218%%


  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

